# Generated by Django 4.2.11 on 2026-05-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_materialcomment'),
        ('komunitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komunitasmessage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komunitas_messages', to='courses.course'),
        ),
    ]
