# Generated by Django 4.2.11 on 2026-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('system_instruction', models.TextField(default='Kamu adalah asisten AI di Sora LMS, sebuah platform pembelajaran online. Bantu siswa, guru, dan admin dengan pertanyaan seputar pembelajaran, materi pelajaran, dan penggunaan platform. Jawab dalam Bahasa Indonesia yang ramah dan jelas.', help_text='Instruksi sistem untuk AI (hidden prompt)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
