# Generated by Django 4.2.11 on 2026-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_add_ai_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='API key untuk Gemini', max_length=200),
        ),
    ]
